name: lectures-assistant

services:
  lectures-assistant:
    image: giovanni653/lectures-assistant:latest
    container_name: lectures-assistant
    ports:
      - "3000:3000"
    volumes:
      - lectures-data:/data
    restart: unless-stopped

volumes:
  lectures-data:
